### ISSUE TITLE
Missing libz/libbz2 static libraries?

### ISSUE THREAD

**Issue by ChristopherWilks** [splatlab/squeakr#1]
I cloned the repo today and when I ran make it complained about not finding the libz/libbz2 static libs in the libs/ subdir.  I didn't see instructions on how to make those.

~~~~
g++ -std=c++11 -Wall -Ofast -m64 -I. -Wno-unused-result -Wno-strict-aliasing main.cc hashutil.cc threadsafe-gqf/gqf.c  -lpthread -lssl -lcrypto -lboost_system -lboost_thread libs/libbz2.a libs/libz.a -o main
g++: error: libs/libbz2.a: No such file or directory
g++: error: libs/libz.a: No such file or directory
make: *** [main] Error 1
~~~~

What am I missing?

Thanks,
Chris

**Comment by prashantpandey** [comment]
I just pushed the missing libraries. It should build now. Let me know if you have any issues.

**Comment by ChristopherWilks** [comment]
thanks! it compiles now.
