### ISSUE TITLE
Max Kmer length 

### ISSUE THREAD

**Issue by taranglute** [splatlab/squeakr#23]
Hi 
I am doing analysis on kmer counting tool and squeakr one of it. I am trying to find out max kmer length for your squeakr. 

What is the max kmer length for squeakr or Can you please help me out on this.

Regards
Tarang

**Comment by prashantpandey** [comment]
Hi,

Squeakr supports k-mer sizes up to 128 (i.e., K <= 128). However, currently, we have two separate branches. If you want to count k-mers with K <=64 you can use the code from `master` branch. 
If you want to count k-mers with K >64 (and smaller than 128) then you can use the code from the branch `large-K`.

Also, we are working on to integrate these two branches. So, in the future, you there will be just one branch that can count k-mers up to K<=128.

Thanks,
Prashant
