### ISSUE TITLE
Doc command line doesn't much help 

### ISSUE THREAD

**Issue by tseemann** [splatlab/squeakr#26]
There doesn't seem to be command lines in your current release, depsite the docs referring to them?

Can you make a new release if things have changed. Needed for packaging in brew/conda.

```
%  squeakr-count  -h
./squeakr-count [OPTIONS]
file format   : 0 - plain fastq, 1 - gzip compressed fastq, 2 - bzip2 compressed fastq
CQF size      : the log of the number of slots in the CQF
num of threads: number of threads to count
file(s)       : "filename" or "dirname/*" for all the files in a directory
```

**Comment by tseemann** [comment]
I've done one for 0.5 here: https://github.com/brewsci/homebrew-bio/pull/68

Ping me here when you make a new release.

**Comment by prashantpandey** [comment]
Hi @tseemann , we have now integrated a command-line interface in Squeakr in the latest release.

Thanks,
Prashant

**Comment by tseemann** [comment]
Thanks @prashantpandey  - trying to update package for 0.6 now.
