### ISSUE TITLE
squeakr-query "Not Find: 0"

### ISSUE THREAD

**Issue by nsohail19** [splatlab/squeakr#30]
Whenever I have tried to query for a specific sequence using squeakr-query, it returns with "Not find: 0". I have tried sequences that are from the fastq files as well as sequences that should not be found in the genome, but I get the same result each time.

In addition, when I try to use squeakr-query using a sequence from the exact branch, it gives me the following error:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoll
Aborted

**Comment by prashantpandey** [comment]
Hi @nsohail19,

Could you please tell me the set of steps you executed, like `squeakr-count` and `squeakr-query` exact commands?

Thanks,
Prashant

**Comment by nsohail19** [comment]
My commands for squeakr-count were like this:
./squeakr-count -g -k 30 -s 30 -t 3 -o HGGs/squeakr_output/ HGGs/SRR7050122_1.fastq.gz

And for squeakr-query, like this:
./squeakr-query -f HGGs/squeakr_output/SRR7050122_1.fastq.gz.ser -k 30 -n 1 -r ACAATGGCCCAGTGGACAGCTGTGCACTCT

**Comment by prashantpandey** [comment]
Hi @nsohail19,

In the command for query, the `-r` is to specify if you want to query random k-mers or existing k-mers. 
```0 means query existing k-mers and 1 means query random k-mers.```

So, based on the command you gave it seems the value of `-r` will be invalid. 

Currently, the query command doesn't take as input a string.
We will soon release a new API which will support specifing a query string. 

Thanks,
Prashant
