### ISSUE TITLE
Update release?

### ISSUE THREAD

**Issue by johnlees** [splatlab/squeakr#35]
I have been unable to use v0.5 (currently on bioconda and the most recent release), but the current master branch works nicely (which I think is about 120 commits ahead of this).

Are you planning to make an updated release tagging this newer version? This would be really helpful re: bioconda packaging too.

**Comment by rob-p** [comment]
Hi @johnlees -- yes, we will definitely do this soon.  Tagging @prashantpandey, @rtjohnso & @fataltes in case they get to this before I can.

**Comment by rob-p** [comment]
@prashantpandey --- let me know when you push the fix for the lognumslots script and then we can cut a new release.  Also, what do you think would be required to fix the "long read buffer" problem once and for all?

**Comment by johnlees** [comment]
Hi again,
Any update on the release? I noticed the current version branch has recently been merged.
I have a package I'd like to make depend on squeakr (and mantis) which I am keen to release.
Thank you!

**Comment by prashantpandey** [comment]
Hi @johnlees , I have tagged the new release V0.6. 

Thanks,
Prashant

**Comment by johnlees** [comment]
Thank you!

**Comment by johnlees** [comment]
BTW I have updated the bioconda package to this new version. 

In doing so I noticed that OS X was no longer supported as it doesn't have `posix_fallocate()`. Not a problem, but thought I would note it here just in case this was unintended or something you wanted to change!
