### ISSUE TITLE
Can't install on OSX, expected identifier FREAD

### ISSUE THREAD

**Issue by yeredh** [splatlab/squeakr#36]
I get the following error message when I try to install squeaker on my laptop.

I'm using macOS Sierra 10.12.6

```
vpn5-210:squeakr-master yeredh$ make squeakr

g++ -std=c++11 -Wall   -Ofast -msse4.2 -D__SSE4_2_ -m64 -I. -Iinclude  -c -o obj/count.o src/count.cc

In file included from src/count.cc:39:

include/gqf_cpp.h:34:2: error: expected identifier

        FREAD

        ^

/usr/include/sys/fcntl.h:110:16: note: expanded from macro 'FREAD'

#define FREAD           0x0001

                        ^

1 error generated.

make: *** [obj/count.o] Error 1
```

**Comment by prashantpandey** [comment]
Hi @yeredh , I am not able to reproduce this error on a linux.
I will try and reproduce this on a MAC.

Thanks,
Prashant

**Comment by tseemann** [comment]
@yeredh please install the Brew package manager (See https://brew.sh) then `brew install brewsci/bio/squeakr`

**Comment by yeredh** [comment]
Hello @tseemann, I was able to install squeakr using brew.
