### ISSUE TITLE
Assertion `new_value < current_remainder' failed.  

### ISSUE THREAD

**Issue by MitraDarja** [splatlab/squeakr#46]
Hi, 

I run in the following error when running squeakr:
```squeakr: src/gqf/gqf.c:1359: int insert1(QF*, __int128 unsigned, uint8_t): Assertion `new_value < current_remainder' failed.
Aborted (core dumped)```

My command is:
`./squeakr count -k 20 -e -n  -t 1 -o data/tmp.squeakr SRR1292579.fastq.gz`

I also tried to not use the flags n and e and tried to use -c 50, but the error remained the same.

(SRR1292579.fastq.gz is downloaded from the sra.)

I am using the master branch and the test case runs through without an error, also when I use k >= 22 it seems to work fine, but from k<22 I get the error message above.

Do you have any idea what is causing this?

**Comment by rmccoy7541** [comment]
I am encountering exactly the same error.

**Comment by prashantpandey** [comment]
Hi @MitraDarja, sorry for the late reply. 
I just downloaded "SRR1292579.fastq.gz" and looking into the issue. I assume you got the error with K=21?

Hi @rmccoy7541, did you have the same setup (fastq file and K-mer size) or did you see the issue in a completely different setup?

**Comment by rmccoy7541** [comment]
It was a different setup for me... I converted these data (https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=ERR3242275) to a FASTQ then ran:
```
[rmccoy22@jhu.edu@rmccoy22-dev kmer]$ ~/code/squeakr/squeakr count -k 48 -s 20 -t 1 -o test HG02384.fastq
[2020-12-16 16:46:04.130] [squeakr_console] [info] Reading from the fastq file and inserting in the CQF.
squeakr: src/gqf/gqf.c:1359: int insert1(QF*, __int128 unsigned, uint8_t): Assertion `new_value < current_remainder' failed.
Aborted
```
I get the same error regardless of the input parameters. The one exception is that `squeakr-exact` does not produce this error, but also does not work for kmer sizes > 32.

**Comment by prashantpandey** [comment]
Hi @rmccoy7541 and @MitraDarja ,

Thanks for pointing out this issue. It turns out that this assertion was in the wrong place and was getting triggered for a corner case when it shouldn't have been called. I have pushed a change to the master branch. 

Please let me know if it fixes the issue.

Thanks,
Prashant

**Comment by MitraDarja** [comment]
Thanks for fixing this, it is working now. :smiley:
