### ISSUE TITLE
segfault when run on a FASTA file

### ISSUE THREAD

**Issue by sjackman** [splatlab/squeakr#8]
```
❯❯❯ ./main 0 20 1 test.fa
Reading from the fastq file and inserting in the QF
[1]    62215 segmentation fault  ./main 0 20 1 test.fa
```

**Comment by prashantpandey** [comment]
Squeakr currently only supports fastq file formats. Added a note in the README.

**Comment by sjackman** [comment]
Can you prevent it from segfaulting when reading a FASTA file, and instead produce an error message?
